### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [yuya-t1201/WorkOasis#87]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
探すための機能は実装されているようです。
まだコンテンツ量が少ないので、探そうとしたユーザーからするとどうすればいいのかわからなくなりそうかなと思います。
そのため、初期データのコンテンツ量を増やすことを優先的に進めていきましょう。
また下記に技術的にプラスした方がいい部分があるので確認して見てください。

## 静的コードチェックが入っている
rubocop導入されているようですが、まだチェックが通ってない部分もあるのでチェックしましょう。

## 就活において十分な技術力を示せる機能を実装しているか
GoogleMap導入したのはいいポイントですね。
ただまだそれを生かせてないので、より探しやすくなるように技術的にプラスアルファを加えていきましょう。
- Mapの画面に検索窓を設けて、場所情報を打ってもらいその場所をマップの中心になるようにする。
- Mapからspot新規登録できるようにする
- ピンが１種類なので、spotの種別でピンの種類を変えるなどする
- spot一覧画面にも検索機能を設ける（登録されているデータを用いてオートコンプリート機能にする）
- spot情報について、ユーザーが知りたい情報を項目として設けて、探せるようにする
- spot評価に関して、星を使って評価するだけだとせっかくのデータがもったいないので、他に評価する項目を考えて2,3つほど加えてあげましょう。そしてそれを検索する際にデータに活かしましょう。

その他下記に気になる点を挙げたのでご確認ください。
- 各々のcontrollerで共通処理になっているアクションの処理はcallbackを利用して共通化しましょう
- workspaces_controllerのcreateアクションはcurrent_userのアソシエーションを使って変数を定義をまとめましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
下記に気になる点を挙げたのでご確認ください。
- TOPページがアプリの紹介だけで、メイン機能への導線が遠いので、アプリの機能への導線などのヘッダー情報を入れてあげましょう。
- Map上に登録されているspot情報はクリックすると、Mapページ下部に簡単な情報を表示するようにしましょう。（詳細ページへのリンクをそこに載せる）
- 一覧ページのspot情報の項目のUIがちょっと明るすぎて違和感があるので、全体のUIに合うような形にしましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by yuya-t1201** [comment]
レビューして頂きありがとうございます。
issuesに登録致しました。
本リリースは約一ヶ月後の11/11を予定しております。

アドバイスしていただいた部分を反映させ、より良いアプリになるように尽力いたします。
今後ともどうぞよろしくお願いいたします！
